#!/bin/bash

wallpapers=$HOME'/Pictures/Wallpapers/'
currentWall=$HOME'/Pictures/current-wallpaper/'
wallfile=$HOME'/Pictures/current-wallpaper/wallpaper.jpg'

rm $wallfile 
shuf -n 1 -e $wallpapers/* | xargs -i cp -r {} $wallfile
gsettings set org.gnome.desktop.background picture-uri "file://$wallfile"
